#%RAML 1.0 Library

types:<%  @model_types.each do |name , type| %><% name = (name.gsub("*","").gsub("[]"," ")).camelize %><% type = type.split(" ")[0] %>
  <%= name %>:
    description: |
      Description of <%= name %>.
    type: <%= type =  type.start_with?("ref:") ?(type.split(":")[1].split(".")[0]+"_"+type.split(":")[1].split(".")[1]).camelize : type %><% if type=="number" %>
    minimum: 1
    maximum: 9999999999    <% end %>
    <% if type=="string" %>minLength: 0
    maxLength: 9999999999
    <% end %><% end %>
  <%  @models.each do |entity, model| %>
  <%= entity.camelize %>:
    (table):
      name: <%= entity.underscore %>
    type: object
    description: |
      Base entity for generate.
    properties:
      <% model.each do |name , type| %><%= name.split(":").last %>:<% if name.include?("*")%>
        (pk):
          identity: <%=type.include?("identity")%><% end %><% if type.start_with?("ref:") %>
        (fk):
          table: <%= type.split(":")[1].split(".")[0].underscore if type.start_with?("ref:") %>
          column: <%=  type.split(":")[1].split(".")[1].underscore if type.start_with?("ref:") %><% end %>
        type: <%= (name.split(":").first.gsub("*","")) %>
      <% end %>
<% end %>