#%RAML 1.0 Library

types:<%  @model_types.each do |name , type| %><% name = (name.gsub("*","").gsub("[]"," ")).camelize %><% typeRoot = type.split(" ")[0] %>
  <%= name %>:
    description: |
      Description of <%= name %>.
    type: <%= typeRoot =  typeRoot.start_with?("ref:") ?(typeRoot.split(":")[1].split(".")[0]+"_"+typeRoot.split(":")[1].split(".")[1]).camelize : typeRoot %><% if typeRoot=="number" %>
    <%= type.split(" ").select{|value| value.start_with?("minimum:")}.size != 0 ? type.split(" ").select{|value| value.start_with?("minimum:")}.first.to_s.sub(":",": ") : "minimum: 0"  %>
    <%= type.split(" ").select{|value| value.start_with?("maximum:")}.size != 0 ? type.split(" ").select{|value| value.start_with?("maximum:")}.first.to_s.sub(":",": ") : "maximum: 99999999999"  %>
    <%= type.split(" ").select{|value| value.start_with?("multipleOf:")}.first.to_s.sub(":",": ")%><% end %><% if typeRoot=="string" %>
    <%= type.split(" ").select{|value| value.start_with?("minLength:")}.size != 0 ? type.split(" ").select{|value| value.start_with?("minLength:")}.first.to_s.sub(":",": ") : "minLength: 0"  %>
    <%= type.split(" ").select{|value| value.start_with?("maxLength:")}.size != 0 ? type.split(" ").select{|value| value.start_with?("maxLength:")}.first.to_s.sub(":",": ") : "maxLength: 1024"  %>
    <% end %>
    <% end %>
  <%  @models.each do |entity, model| %>
  <%= entity.camelize %>:
    (table):
      name: <%= entity.underscore %>
    type: object
    description: |
      Base entity for generate.
    properties:
      <% model.each do |name , type| %><%= name.split(":").last %>:<% if name.include?("*")%>
        (pk):
          identity: <%=type.include?("identity")%><% end %><% if type.start_with?("ref:") %>
        (fk):
          table: <%= type.split(":")[1].split(".")[0].underscore if type.start_with?("ref:") %>
          column: <%=  type.split(":")[1].split(".")[1].underscore if type.start_with?("ref:") %><% end %>
        type: <%= (name.split(":").first.gsub("*","")) %>
      <% end %>
<% end %>