#%RAML 1.0 Library

uses:
  base: ./base.raml
types:
  <%= @entity %>GetData:
    description: |
      One <%= @entity %>
    type: object
    properties:
      data:
        type: <%= @entity %>Get

  <%= @entity %>Get:
    type: object
    description: |
      Example description of the object.
    properties:
      <% for attribute in @attributes %><%= attribute[:name].underscore %>:
        type: base.<%= attribute[:name] %>
      <% end %>
    example:
      {}