#%RAML 1.0 Library

uses:
  base: ./base.raml
types:
  <%= @entities %>PostData:
    description:
    type: object
    properties:
      data:
        type: <%= @entity %>Post

  <%= @entity %>Post:
    type: object
    description: |
      Example description of the object.
    properties:
      <% for attribute in @attributes %><%= attribute[:name].underscore %>?:
        type: base.<%= @entity %><%= attribute[:name] %>
      <% end %>
    example:
      {
      }
