#%RAML 1.0
title: <%= @title %>
description: |
  <h2><%= @title %></h2>
  <p>
  <%= @description %>
  <p>
  Important: this service doesn't support the "self-assisted" customer point of view, so, it does not filter
  data based on customer's authorization

version: <%= @version %>
(project):
    group: <%= @group %>
    artifact: <%= @artifact.downcase %>
    name: <%= @artifact.camelize %>
mediaType: <%= @mediaType %>
protocols:
  - HTTP
  - HTTPS
baseUri: 'http://{host}:{port}/<%= @baseUri %>/<%= @entities %>/{version}'

baseUriParameters:
  host:
    type: string
  port:
    type: integer

uses:
  filterType: ./traits/filter_type.raml
  errorWarning: ./libraries/error_warning.raml
  <%  @file_yaml["microservice"].each do |entity| %><%   entity = entity.camelize %><%  entities = entity.pluralize %>
  <%= entities %>Get: ./types/<%= entities %>_get.raml
  <%= entity %>Get: ./types/<%= entity %>_get.raml
  <%= entities %>Post: ./types/<%= entities %>_post.raml
  <%= entities %>PostId: ./types/<%= entities %>_postId.raml
  <%= entities %>Put: ./types/<%= entities %>_put.raml
  <%= entities %>PutId: ./types/<%= entities %>_putId.raml
  <% end %>

  sortable: ./traits/sortable.raml
  paginatedContent: ./traits/paginated-content.raml
  viewable: ./traits/viewable.raml
  expandable: ./traits/expandable.raml
  simplifiable: ./traits/simplifiable.raml
  base: ./types/base.raml

resourceTypes:
  simple_colleccion: !include resourceTypesMCS/simple_collection.raml
  static_collection: !include resourceTypesMCS/static_collection.raml
  item: !include resourceTypesMCS/item.raml
 <%  @file_yaml["microservice"].each do |entity| %><%  entity_camelize = entity.camelize %><%  entities = entity_camelize.pluralize %>
/<%= entities.downcase %>:
  (entity): base.<%= entity.capitalize()  %>
  type: { simple_colleccion: { "baseUri": 'http://{host}:{port}/<%= @baseUri %>/<%= entities %>/{version}' } }
  description: |
    
  get:
    description: |
  
    is:
      [
        <% for filter in filters %>filterType.<%= filter[:filterType] %>: {attribute : <%= filter[:attribute] %>, required: <%= filter[:required] %>},<% end %>
        
        sortable.SortCriteria: {fields: contact_date_time},
        simplifiable.SimplificationCriteria: {fields : client_id | contact_date | reference},
        paginatedContent.PaginatedContent
      ]
    responses:
      200:
        description: |
          The request was successfully
        body:
          application/json:
            type: <%= entities %>Get.<%= entities %>GetData


  post:
      body:
          application/json:
            description:  Customer request to create
            type: <%= entities %>Post.<%= entities %>PostData
      responses:
       201:
         description: |
            The request was accepted.
         body:
          application/json:
                  type: <%= entity_camelize %>Get.<%= entity_camelize %>GetData
       405:
         description: |
            Invalid Parameters
       409:
         description: |
            There is already a transfer request created with the channel reference number

  /{<%= pk =  entity.downcase+"_"+@file_yaml["entities"][entity].keys.select{|name| name.include?("*") }[0].gsub("*","") %>}:
    type:  { item : { "resourceId" : '<%= pk %>' } }
    (entity): base.<%= entity.capitalize()  %>
    get:
      description: |
        Gets the request associated with identified as part the url.
      responses:
        200:
          description: |
            <%= entities %> Found
          body:
            application/json:
              type:  <%= entity_camelize %>Get.<%= entity_camelize %>GetData
        400:
          description: |
            the request has an incorrect format
        404:
          description: |
              Resource not found
    put:
      description: |
        Update <%= entities %>
      body:
          application/json:
            type: <%= entities %>Put.<%= entities %>PutData
      responses:
        200:
          description: |
            The request was update successfully
          body:
            application/json:
              type:  <%= entity_camelize %>Get.<%= entity_camelize %>GetData
        400:
          description: |
              The request has an incorrect format

    delete:
      description: |
              Request to remove Customers
      responses:
        200:
          description:  |
              The request has bee successfull
        404:
          description: |
              There is no transfer request associated with the specified identifier
<% end %>